### Field info

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

data = pd.read_csv('data/coupons.csv')

In [4]:
def print_unique_values_for_object_columns(df):
    """
    Print unique values for each column that is of type 'object' in the DataFrame.
    
    Args:
        df (pandas.DataFrame): The DataFrame to analyze
    """
    # Get columns that are of object type (typically strings/categorical)
    object_columns = df.select_dtypes(include=['object']).columns
    
    print(f"Found {len(object_columns)} object-type columns:")
    print("=" * 60)
    
    for col in object_columns:
        unique_vals = df[col].unique()
        null_count = df[col].isnull().sum()
        
        print(f"\nColumn: '{col}'")
        print(f"Number of unique values: {len(unique_vals)}")
        print(f"Missing values: {null_count}")
        print(f"Unique values: {list(unique_vals)}")
        print("-" * 40)
    
    return object_columns

# Call the function to analyze the data
print_unique_values_for_object_columns(data)

Found 18 object-type columns:
============================================================

Column: 'destination'
Number of unique values: 3
Missing values: 0
Unique values: ['No Urgent Place', 'Home', 'Work']
----------------------------------------

Column: 'passanger'
Number of unique values: 4
Missing values: 0
Unique values: ['Alone', 'Friend(s)', 'Kid(s)', 'Partner']
----------------------------------------

Column: 'weather'
Number of unique values: 3
Missing values: 0
Unique values: ['Sunny', 'Rainy', 'Snowy']
----------------------------------------

Column: 'time'
Number of unique values: 5
Missing values: 0
Unique values: ['2PM', '10AM', '6PM', '7AM', '10PM']
----------------------------------------

Column: 'coupon'
Number of unique values: 5
Missing values: 0
Unique values: ['Restaurant(<20)', 'Coffee House', 'Carry out & Take away', 'Bar', 'Restaurant(20-50)']
----------------------------------------

Column: 'expiration'
Number of unique values: 2
Missing values: 0
Unique values: ['1d', '2h']
----------------------------------------

Column: 'gender'
Number of unique values: 2
Missing values: 0
Unique values: ['Female', 'Male']
----------------------------------------

Column: 'age'
Number of unique values: 8
Missing values: 0
Unique values: ['21', '46', '26', '31', '41', '50plus', '36', 'below21']
----------------------------------------

Column: 'maritalStatus'
Number of unique values: 5
Missing values: 0
Unique values: ['Unmarried partner', 'Single', 'Married partner', 'Divorced', 'Widowed']
----------------------------------------

Column: 'education'
Number of unique values: 6
Missing values: 0
Unique values: ['Some college - no degree', 'Bachelors degree', 'Associates degree', 'High School Graduate', 'Graduate degree (Masters or Doctorate)', 'Some High School']
----------------------------------------

Column: 'occupation'
Number of unique values: 25
Missing values: 0
Unique values: ['Unemployed', 'Architecture & Engineering', 'Student', 'Education&Training&Library', 'Healthcare Support', 'Healthcare Practitioners & Technical', 'Sales & Related', 'Management', 'Arts Design Entertainment Sports & Media', 'Computer & Mathematical', 'Life Physical Social Science', 'Personal Care & Service', 'Community & Social Services', 'Office & Administrative Support', 'Construction & Extraction', 'Legal', 'Retired', 'Installation Maintenance & Repair', 'Transportation & Material Moving', 'Business & Financial', 'Protective Service', 'Food Preparation & Serving Related', 'Production Occupations', 'Building & Grounds Cleaning & Maintenance', 'Farming Fishing & Forestry']
----------------------------------------

Column: 'income'
Number of unique values: 9
Missing values: 0
Unique values: ['$37500 - $49999', '$62500 - $74999', '$12500 - $24999', '$75000 - $87499', '$50000 - $62499', '$25000 - $37499', '$100000 or More', '$87500 - $99999', 'Less than $12500']
----------------------------------------

Column: 'car'
Number of unique values: 6
Missing values: 12576
Unique values: [nan, 'Scooter and motorcycle', 'crossover', 'Mazda5', 'do not drive', 'Car that is too old to install Onstar :D']
----------------------------------------

Column: 'Bar'
Number of unique values: 6
Missing values: 107
Unique values: ['never', 'less1', '1~3', 'gt8', nan, '4~8']
----------------------------------------

Column: 'CoffeeHouse'
Number of unique values: 6
Missing values: 217
Unique values: ['never', 'less1', '4~8', '1~3', 'gt8', nan]
----------------------------------------

Column: 'CarryAway'
Number of unique values: 6
Missing values: 151
Unique values: [nan, '4~8', '1~3', 'gt8', 'less1', 'never']
----------------------------------------

Column: 'RestaurantLessThan20'
Number of unique values: 6
Missing values: 130
Unique values: ['4~8', '1~3', 'less1', 'gt8', nan, 'never']
----------------------------------------

Column: 'Restaurant20To50'
Number of unique values: 6
Missing values: 189
Unique values: ['1~3', 'less1', 'never', 'gt8', '4~8', nan]
----------------------------------------

Index(['destination', 'passanger', 'weather', 'time', 'coupon', 'expiration',
       'gender', 'age', 'maritalStatus', 'education', 'occupation', 'income',
       'car', 'Bar', 'CoffeeHouse', 'CarryAway', 'RestaurantLessThan20',
       'Restaurant20To50'],
      dtype='object')